include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: ignore
    library_private_types_in_public_api: info
    prefer_const_constructors: info
    prefer_const_constructors_in_immutables: info
    prefer_interpolation_to_compose_strings: info
    sort_child_properties_last: info
    use_build_context_synchronously: info
    use_key_in_widget_constructors: info

analyzer:
  errors:
    avoid_print: info
    library_private_types_in_public_api: info
    prefer_const_constructors: info
    prefer_const_constructors_in_immutables: info
    prefer_interpolation_to_compose_strings: info
    sort_child_properties_last: info
    use_build_context_synchronously: info
    use_key_in_widget_constructors: info
