apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluttercommerce-deployment
  labels:
    app: fluttercommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fluttercommerce
  template:
    metadata:
      labels:
        app: fluttercommerce
    spec:
      containers:
        - name: fluttercommerce
          image: ${{ secrets.DOCKER_USERNAME }}/fluttercommerce:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fluttercommerce-service
  labels:
    app: fluttercommerce
spec:
  selector:
    app: fluttercommerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
