name: fluttercommerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 3.22.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  web: ^0.5.1
  mockito: ^5.0.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
