apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluttercommerce
  namespace: group20
  labels:
    app: fluttercommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluttercommerce
  template:
    metadata:
      labels:
        app: fluttercommerce
    spec:
      containers:
        - name: fluttercommerce
          image: giannivanlooij/fluttercommerce:latest
          ports:
            - name: web
              containerPort: 80
          env:
            - name: ENV_VAR
              value: "value"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: registry-credentials
