apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluttercommerce
  labels:
    app: fluttercommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fluttercommerce
  template:
    metadata:
      labels:
        app: fluttercommerce
    spec:
      containers:
        - name: fluttercommerce
          image: ${{ secrets.DOCKER_USERNAME }}/fluttercommerce:latest  # Docker Hub repo location is used
          ports:
            - containerPort: 8080
          env:
            - name: ENV_VAR
              value: "value"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20