apiVersion: v1
kind: Service
metadata:
  name: fluttercommerce-service
spec:
  selector:
    app: fluttercommerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007 # you can specify a nodePort or let Kubernetes assign one
  type: NodePort
