name: Deploy for FlutterCommerce

on:
  push:
    branches: [ develop, docker, main ]
#  pull_request:
#    branches: [ develop, main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.30.0' # Specify the latest stable version
          kubernetes version: 'latest'
          driver: 'docker'

      - name: Wait for Minikube to start
        run: |
          until kubectl get nodes; do sleep 1; done

      - name: Verify Minikube status
        run: kubectl get nodes