name: Deploy

on:
  workflow_run:
#    if the ci pipeline works. then this job gets triggerd
#    the reason why the pipeline is not more split is because the lock file is preventing the pipeline from being split (for example tries to build for the file build.yml but if another file is running the pub spec then it wont work)
    workflows: ["CI for FlutterCommerce"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fluttercommerce:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/fluttercommerce:latest


