name: Deploy for FlutterCommerce

on:
  workflow_run:
    workflows: ["CI for FlutterCommerce"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube-version: 'latest'
          kubernetes-version: 'latest'
          driver: 'docker'

      - name: Wait for Minikube to start
        run: |
          until kubectl get nodes; do sleep 1; done

      - name: Verify Minikube status
        run: kubectl get nodes
