name: CI for FlutterCommerce

on:
  push:
    branches: [ develop, docker ]
  pull_request:
    branches: [ develop, main ]

jobs:
  security_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Scout
        run: curl -sSL https://get.docker.com/ | sh

      - name: Run Docker Scout analysis
        run: docker scout quickview --image ${{ secrets.DOCKER_USERNAME }}/fluttercommerce:latest


