name: Docker Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker build -t my-docker-flutter:latest .

  unittesting:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          docker run --rm my-docker-flutter:latest flutter test

  prepare_release:
    runs-on: ubuntu-latest
    needs: unittesting
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare release
        run: |
          # Add commands to prepare the release
          echo "Preparing release"

  infrastructure_testing:
    runs-on: ubuntu-latest
    needs: prepare_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test infrastructure
        run: |
          # Add commands to test the infrastructure
          echo "Testing infrastructure"

  push_dockerhub:
    runs-on: ubuntu-latest
    needs: infrastructure_testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to DockerHub
        run: |
          docker tag my-docker-flutter:latest my-dockerhub-repo/my-docker-flutter:latest
          docker push my-dockerhub-repo/my-docker-flutter:latest
