name: CI for FlutterCommerce

on:
  push:
    branches: [ develop, docker ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            giannivanlooij/fluttercommerce:latest
            giannivanlooij/fluttercommerce:${{ github.run_number }}

  unittesting:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Unit Tests
        run: flutter test

  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    needs: build  # This ensures the build job is completed successfully before running this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t giannivanlooij/fluttercommerce:release .

      - name: Install Goss
        run: curl -fsSL https://goss.rocks/install | sudo sh

      - name: Validate with Goss
        run: goss validate

  infrastructure_testing:
    name: Infrastructure Testing
    runs-on: ubuntu-latest
    needs: build  # This ensures the build job is completed successfully before running this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Goss
        run: curl -fsSL https://goss.rocks/install | sudo sh

      - name: Validate with Goss
        run: goss validate

  push_dockerhub:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    needs: [build, prepare_release]  # This ensures both the build and prepare_release jobs are completed successfully before running this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            giannivanlooij/fluttercommerce:latest
            giannivanlooij/fluttercommerce:${{ github.run_number }}
